### PR TITLE
Add support for LuaLaTeX and XeLaTeX, and automatically uppercase.

### PR DESCRIPTION
**Pull request by matz-e**
Posting this now for review, even though I haven't finished updating the documentation completely. Support for all TeX engines should work, I haven't tested `pdflatex` extensively.

All thesis titles, chapters, table captions are automatically set to uppercase in the running text, and normal case in the table of contents or list of tables, in accordance with Shari.

I had to remove one package, `amssymb`, since it seems to clash with newer packages/engines.

### CODE REVIEW

**Comment by dbrower** [comment]
Hey @matz-e I just noticed this PR---for some reason I missed the email notification. Thanks for updating the class for xetex and luatex. I'm happy to see it.

If it is ready for review I can look at it next week.

**Comment by matz-e** [comment]
@dbrower sorry for taking a bit myself to respond. I've added one more fix to replace `\ifpdf` with a better construct, since it did not work properly for me with `lualatex`.

I think the changes are ready for review! I hope I got the documentation updated correctly, too.

**Comment by dbrower** [comment]
I tried running this on the file in the example directory (after first running `ln -s ../nddiss2e.cls` in that directory to  use the new class file). I am getting a strange error when using pdflatex:

```
$ pdflatex example.tex
[...]
Pagestyle and spacing normal
! Use of \@icentercr doesn't match its definition.
<argument> \def 
                
l.97 \maketitle
```

I'm guessing it is related to `\MakeTextUppercase` since doing a search and replace to remove all those commands makes the error go away. Unsure what the cause is or why it is happening at the moment.

**Comment by matz-e** [comment]
Indeed, I missed that, since I had my own template I tested with. Replacing all `\\` with `\protect\\` in the title definition of the example fixes that. I can add this to the documentation (my own title is long but does not have any linebreaks).

**Comment by matz-e** [comment]
I've fixed the compilation and added notes to the documentation, and reformatted the example file.

On a general note, I use the packages `threeparttable`, `threeparttablex`, and `cleveref` that I think may be useful to mention. The former two I use to add footnotes and general notes to tables, displayed below the table. The latter automatically prefaces references: `\cref{fig:something}` turns into, e.g., `figure 5.1`, and can handle multiple references in one command etc. Thoughts?

**Comment by dbrower** [comment]
An update...While the chapter headings in the text are uppercased, the entries in the table of contents are in whatever case was typed in the document. I'm waiting for the graduate school to tell me whether that is acceptable or not.

It seems that since this class file was originally made (late '90s, early 2000s), many latex packages for customizing have been introduced (I have the caption package in mind). I'm not against moving to using more of these rather than making custom commands. My only concern is backward compatibility---ideally any changes in behavior would have a note describing how to modify old documents to work with the new method.

**Comment by matz-e** [comment]
Thanks for the update!

According to our mail exchange from June 6, not having all uppercase table of contents should be fine, as long as done consistently. I tried to add this to the documentation, too.

Using newer packages like `caption` would be nice, although I think it will be a lot of work and probably amount to a full re-write?

**Comment by dbrower** [comment]
yeah, you have a good point. I'll merge this as-is.

I had a problem with compiling the example document with xetex. Since xetex is not (officially?) supported, I'll do the merge and then make an issue with my problem.

**Pull request merged**
