### PR TITLE
Small adjustments.

### PR DESCRIPTION
**Pull request by matz-e**
The documentation on this could probably use another update, but before moving into that direction, I'd like to see if these changes make sense?

* Remove pdfx package, which impacted the review process. The inclined
user may opt to include it themselves.
* Include hyperref rather than calling its setup.
* Include enumitem to allow list manipulation (this clashes with how
lists were re-defined before).
* Remove package enumerate.
* Make the list environments single-spaced by using hooks rather than redefinitions.
* Mention threeparttable in the documentation and set the environment
up in accordance with the style guide.

### CODE REVIEW

**Comment by dbrower** [comment]
Ah, you are doing the carrying out the plan of updating the package to use modern LaTeX-isms. I am really happy you are doing this work.

I have one comment with removing the pdfx package. As I recall, it was added to help support the creation of PDF/A documents. If fonts were not embedded in the document, the process the Graduate School uses to produce PDF/A documents from PDF documents would rasterize the page, producing jagged fonts and images that people disliked. I think the pdfx package was forcing fonts to be embedded (??). Do you happen to know of another way to either generate or ease the generation of PDF/A files?

**Comment by matz-e** [comment]
Well, this is probably as far as modernizing as I go.

In the style-check, Shari mentioned that she had to remove the PDF/A setting to be able to comment  on the thesis, and that it would be nice to add some additional metadata for the final submission, where she does not change the format, to avoid glitches?

I can add the pdfx package conditionally for the final submission (noinfo) and try to figure out how to best set the rest of the metadata.

**Comment by dbrower** [comment]
If the pdfx is causing Shari problems, then it needs to go. I added it as an experiment to solve the  the embedded font problem. I wonder how well only using pdfx for the final submission will work.

Do you want me to merge this PR now and make another one for the documentation?

**Comment by matz-e** [comment]
The pdfx sounds like a good idea for the `noinfo` option, if it helps with the conversion down the line. Re-reading Shari's email, she more alerted me to the fact that she had to change the format from pdf/a->pdf to be able to comment, and that may mess things up a little?

I can add some examples for the threeparttable in a separate PR and fix the lists of packages included.

**Comment by dbrower** [comment]
I'll merge this for now. And someone can revisit the PDF/A later, maybe by only including it with the `noinfo` option.

**Pull request merged**
